# Generated by Django 5.1 on 2024-11-27 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0002_remove_responsecode_image_url_responsecode_image_jpg_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedlist',
            name='codes',
        ),
        migrations.AddField(
            model_name='savedlist',
            name='codes',
            field=models.JSONField(default=list),
        ),
    ]
